# Generated by Django 5.2.5 on 2025-08-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
