# Generated by Django 5.2.5 on 2025-08-25 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_phone_restaurant_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_tumber',
            new_name='phone_number',
        ),
    ]
